### ISSUE TITLE
Add text align feature

### ISSUE THREAD

**Issue by Id0ntwantt0telly0u** [ZechCodes/pil-multiline-writer#1]
Allow text to be aligned left, right, or centered.

**Comment by ZechCodes** [comment]
Implemented alignment (left, center, and right). Also reworked how settings are applied and how padding is set. Using methods and properties instead of function arguments.

```python
writer = LineWriter(image)
writer.alignment = Alignment.CENTER # Alignment.LEFT and Alignment.RIGHT also available
writer.set_padding(top=10, bottom=15, sides=30) # Padding is set to top 10, left 30, bottom 10, and right 30
writer.line_scaling = 1.5
writer.offset_top = 10 # Shifts the text down 10px
writer.text("This is my message", fill="black")
image.show()
```

You can find full documentation in the code for now. Need to update the docs, will do after I complete the other features.

Commit resolving issue #3 
Download the updated source https://github.com/ZechCodes/pil-multiline-writer/archive/master.zip
